.deploy: &deploy
  image: dock.mau.dev/tulir/docker-mdbook
  tags: [webdeploy]
  script:
  - rsync -rcthvl bookshelf/ $TARGET/
  - rsync -rcthvl python/ $TARGET/python/
  - mdbook build bridges && rsync -rcthvl --delete dist/bridges/html/ $TARGET/bridges/
  - mdbook build maubot && rsync -rcthvl --delete dist/maubot/html/ $TARGET/maubot/
  - mdbook build gomuks && rsync -rcthvl --delete dist/gomuks/html/ $TARGET/gomuks/

master:
  <<: *deploy
  variables:
    TARGET: /srv/web/docs.mau.fi
  only:
  - master

staging:
  <<: *deploy
  variables:
    TARGET: /srv/web/docs.mau.fi/staging/$CI_BRANCH_NAME
  before_script:
  - mkdir -p $TARGET
  except:
  - master
